name: "cron-randomizer"
description: "Action to randomize the cron schedule."

inputs:
  whatToRandomize:
    description: "What values you want to randomize. Use 1 to randomize, and 0 to leave that value. Eg: y y n n n"
    required: true

  whichCron:
    description: "If there are more than one cronjob, indicate which one you want to randomize (0, 1, 2, 3)."
    required: false
    default: "0"

  file:
    description: "File that will be modified"
    required: false
    default: ${{ github.WORKFLOW_REF }}

runs:
  using: node20
  main: ./dist/index.js
