



on:
  push:
  # schedule:
    # - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          which_cron: 0
          what_to_randomize: "y y n n n"

      - name: Cat workflow
        run: |
          cat .github/workflows/test.yaml

