



on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          which_cron: 0
          what_to_randomize: 1/1/0/0/0

