



on:
  workflow_dispatch:
  push:
  # schedule:
    # - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action
        uses: NeddM/cron-randomizer@development
        with:
          whichCron: 0
          whatToRandomize: "y y n n n"

      - name: Cat workflow
        run: |
          cat .github/workflows/test.yaml

